# syntax=docker/dockerfile:1.6
FROM node:20.11.0-alpine AS base
RUN corepack enable && corepack prepare pnpm@8.15.5 --activate
WORKDIR /app

# -- deps
FROM base AS deps
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY apps/api/package.json apps/api/
COPY packages ./packages
RUN pnpm install --frozen-lockfile --prod=false

# -- build
FROM base AS build
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm --filter @ecopye/database prisma generate
RUN pnpm --filter @ecopye/api build

# -- runtime
FROM node:20.11.0-alpine AS runtime
RUN addgroup -S ecopye && adduser -S ecopye -G ecopye
WORKDIR /app
ENV NODE_ENV=production \
    PORT=3000

COPY --from=build --chown=ecopye:ecopye /app/node_modules ./node_modules
COPY --from=build --chown=ecopye:ecopye /app/apps/api/dist ./apps/api/dist
COPY --from=build --chown=ecopye:ecopye /app/apps/api/package.json ./apps/api/
COPY --from=build --chown=ecopye:ecopye /app/packages ./packages

USER ecopye
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD wget -qO- http://localhost:3000/v1/health || exit 1

CMD ["node", "apps/api/dist/server.js"]
