/**
 * Canonical error codes — stable contract exposed to API consumers.
 * DO NOT rename; only append.
 */
export const ERROR_CODES = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_DEVICE_UNTRUSTED: 'AUTH_DEVICE_UNTRUSTED',

  // OTP
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',

  // KYC
  KYC_INSUFFICIENT: 'KYC_INSUFFICIENT',
  KYC_DOCUMENT_REJECTED: 'KYC_DOCUMENT_REJECTED',
  KYC_ALREADY_VERIFIED: 'KYC_ALREADY_VERIFIED',

  // Wallet / transactions
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_FROZEN: 'WALLET_FROZEN',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  DAILY_LIMIT_EXCEEDED: 'DAILY_LIMIT_EXCEEDED',
  MONTHLY_LIMIT_EXCEEDED: 'MONTHLY_LIMIT_EXCEEDED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  TRANSACTION_ALREADY_PROCESSED: 'TRANSACTION_ALREADY_PROCESSED',
  TRANSACTION_NOT_REVERSIBLE: 'TRANSACTION_NOT_REVERSIBLE',

  // Compliance
  SANCTIONED_COUNTERPARTY: 'SANCTIONED_COUNTERPARTY',
  COMPLIANCE_HOLD: 'COMPLIANCE_HOLD',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',

  // Merchant
  MERCHANT_NOT_ACTIVE: 'MERCHANT_NOT_ACTIVE',
  MERCHANT_MEMBER_FORBIDDEN: 'MERCHANT_MEMBER_FORBIDDEN',

  // Bills / payment providers
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  PROVIDER_REJECTED: 'PROVIDER_REJECTED',
  BILL_REFERENCE_INVALID: 'BILL_REFERENCE_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
